databases:
  - name: smart_learning_assistant
    plan: free
    databaseName: smart_learning_assistant
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn smart_learning_assistant.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
